# https://dependabot.com/docs/config-file/
# https://dependabot.com/docs/config-file/validator/

version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: daily
    default_labels:
      - dependencies
      - dependabot
    version_requirement_updates: increase_versions
    commit_message:
      prefix: chore
      include_scope: true
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
